
#................................................................................
# "/__w/My.CVitae/My.CVitae" is the working directory when using the docker image
# use    Rscript -e "print(getwd())"   in the 'render the curriculum vitae' step
# I have to add this manually in the 'cv.Rmd' file of the 'docs' directory
#
# For the case that I have to use docker credentials see:
#    https://stackoverflow.com/a/64051330/8302386
#................................................................................


on:
  schedule:
    - cron: "0 23 * * SUN"
  push:
    branches: master

name: docker_cv


jobs:
  build:
    name: create the curriculum vitae pdf file
    runs-on: ubuntu-latest
    container:
      image: mlampros/mycvitae:rstudiodev
    steps:
     - uses: actions/checkout@v2
     - name: render the curriculum vitae
       run: |
         Rscript -e "print(getwd())"
         Rscript -e "rmarkdown::render(input = file.path(getwd(), 'docs', 'cv.Rmd'), params = list(work_dir = getwd()))"
     - name: Commit files
       run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add the cv.pdf file to the 'docs' directory of the repository"
          git push
     - name: Upload pdf file
       uses: actions/upload-artifact@v1
       with:
         name: docs
         path: docs/

